export const BLOCK_TYPE_BITCOIN = 'BITCOIN';
export const BLOCK_TYPE_EOS = 'EOS';

export const DRAW_BLOCK_HASH = 'DRAW_BLOCK_HASH';
export const DRAW_SERVICE_PROVIDER_HASH = 'DRAW_SERVICE_PROVIDER';
export const DRAW_BYZNATINE_PROTOCOL = 'DRAW_BYZANTINE_PROTOCOL';